FIND_PATH(HELLO_INCLUDE_DIR hello.h /tmp/demo_3/include/hello)
FIND_LIBRARY(HELLO_LIBRARY libhello.so  /tmp/demo_3/lib)

IF (HELLO_INCLUDE_DIR)
    MESSAGE(STATUS "FOUND HELLO_INCLUDE")
ENDIF (HELLO_INCLUDE_DIR)

IF (HELLO_LIBRARY)
    MESSAGE(STATUS "FOUND HELLO_LIBRARY")
ENDIF (HELLO_LIBRARY)

IF (HELLO_INCLUDE_DIR AND HELLO_LIBRARY)
    SET(HELLO_FOUND TRUE)
ENDIF (HELLO_INCLUDE_DIR AND HELLO_LIBRARY)

IF (HELLO_FOUND)
    IF (NOT HELLO_FIND_QUIETLY)
        MESSAGE(STATUS "Found Hello: ${HELLO_LIBRARY}")
    ENDIF (NOT HELLO_FIND_QUIETLY)
ELSE (HELLO_FOUND)
    IF (HELLO_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find hello library")
    ENDIF (HELLO_FIND_REQUIRED)
ENDIF (HELLO_FOUND)

